### ISSUE TITLE
SelectMenu Improvements Tracking

### ISSUE THREAD

**Issue by emplums** [primer/react#1002]
As part of our [Behaviors Epic]() we would like to address some of the current issues with the SelectMenu component. We'll want to incorporate the new Overlay system work into this issue (which may include props API and visual changes) but I've started this issue to track all work and have started with listing the outstanding feature requests we currently know about 🙌 

Let's add to this issue as we learn more through the Overlay work & planning we do next week.

- [ ] [Perf] Don't render select menu content unless menu is open #946 
- [ ] Fix: onOutsideClick & React Portals #940 
- [ ] Allow consumers to control state of SelectMenu #933 
- [ ] Add `onOpen` and `onClose` callbacks to SelectMenu #932 
- [ ] Add close button to responsive SelectMenu #750

**Comment by colebemis** [comment]
We will soon be deprecating SelectMenu in favor of SelectPanel
