### ISSUE TITLE
Enforce consistent component documentation page structure

### ISSUE THREAD

**Issue by colebemis** [primer/react#1431]
## Problem

The structure of our component documentation pages is inconsistent. 

* Some pages are missing component descriptions, source links, statuses
* Headings are named inconsistently (e.g. `Component props` vs `Props` vs `AvatarStack Component props`)
* Headings are ordered inconsistently (e.g. sometimes props appear before examples and vice versa)

<details>
  <summary>Examples</summary>

| Box | AvatarStack | Details |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/4608155/133693011-1516cb8d-d461-4c8e-97d1-43553fbc1c93.png) | ![image](https://user-images.githubusercontent.com/4608155/133693199-b05fbb47-9973-4a84-b5b2-9ec0b842615d.png) | ![image](https://user-images.githubusercontent.com/4608155/133693305-f6353fa0-c528-4070-b6f2-cf47f4aeb908.png) |

</details>

This inconsistency stems from a lack of guidelines and tooling around component documentation pages.

## Why is this important?

A prerequisite to moving a component to [stable](https://primer.style/contribute/component-lifecycle#stable) is that the documentation for the component is "complete." However, we don't have any guidelines or tooling that document what "complete" documentation looks like for a Primer React component. We need those guidelines before we can consider components "stable."

## Tasks

- [ ] Decide on a structure for component documentation pages
  - See [Radix Primitives](https://www.radix-ui.com/docs/primitives/components/accordion), [Braid](https://seek-oss.github.io/braid-design-system/components/Accordion), [Spectrum](https://react-spectrum.adobe.com/react-spectrum/ActionButton.html), [Primer ViewComponents](https://primer.style/view-components/components/beta/autocomplete), etc. for inspiration
  - Chat with folks working with Primer React and Primer ViewComponents
- [ ] Document the structure for component documentation pages
- [ ] Enforce documentation structure (maybe using a linter?)

**Comment by siddharthkp** [comment]
Should we bring back the template from https://github.com/primer/react/pull/1452?

**Comment by colebemis** [comment]
This will be resolved in the new Primer React docs
