### ISSUE TITLE
Add docs for migrating to system props

### ISSUE THREAD

**Issue by shawnbot** [primer/react#161]
I realized as I was thinking about releasing `v0.0.12-beta` (via #143) that the introduction of "system" props in #155 and #157 represent a very breaking API change, and that we need to fully document what users will need to change if they decide to upgrade. That wasn't going to happen before tomorrow (7/27/18), so we decided to rebase away #155 and push it off to next week's release, pending docs.

#### Tasks
- [ ] Reconsider base styles and whether the `<StyleProvider>` or whatever is necessary.
- [ ] Document the (required?) use of `<StyleProvider>` and/or `<ThemeProvider>`. (This should probably go into the README along with some _very basic_ usage examples.)
- [ ] Make an exhaustive reference of the system props and their values in a table somewhere. We could repurpose the "Utility Props" pages in #155 for this.

We might even want to signal the severity of this change with a minor version bump! 😱  /cc @primer/ds-core
