### ISSUE TITLE
Styled-system upgrade tracking

### ISSUE THREAD

**Issue by shawnbot** [primer/react#168]
### What to do
1. Factor out any instances of `theme.colors.bg` and `theme.colors.border`, since those aren't there anymore. Some components used these to fill in the gaps left by our CSS components. Please leave notes in #161 if you come across any gotchas.

1. Add common system props. See `contributing.md` (introduced in #180) for details.

1. Refactor tests to get them passing again.

    * For components with only system props (system components?), we can get by with snapshot tests for now. Snapshots are stored in git, so we can look at them after the first run (when jest prompts us to update them) and spot-check the files generated in `src/__tests__/__snapshots__` for any potential issues.

    * Use the `expect(render(<X />)).toHaveStyleRule()` to test individual style props. For props that are based on the theme, you can `import theme from '../theme'` and pass `theme={theme}`, then compare the style rule value to the one in the theme. **Note that it's not currently possible to test responsive props.** See #165 for more info.

    * For components that render system components (`X = props => <Block {...props} />`), be sure to spread the base component's `propTypes` into your components' prop-types.

1. Rename all `tag` props to `is` to match styled-system conventions.

### Components
- [x] Avatar (`src/Avatar.js`) @emplums #170 
- [x] Block (`src/Block.js`) @shawnbot #164 
- [x] ~Box (`src/Box.js`) [DELETE] @emplums~ (TBD, see #189)
- [x] BranchName (`src/BranchName.js`) @emplums #178 
- [x] Button (`src/Button.js`) @emplums #181 
- [x] ButtonDanger (`src/ButtonDanger.js`) @emplums #181 
- [x] ButtonLink (`src/ButtonLink.js`) @emplums #181 
- [x] ButtonOutline (`src/ButtonOutline.js`) @emplums #181 
- [x] ButtonPrimary (`src/ButtonPrimary.js`) @emplums #181 
- [x] ~~Caret (`src/Caret.js`) @emplums #184~~
- [x] CaretBox (`src/CaretBox.js`) @emplums @shawnbot (multiple PRs)
- [x] CircleBadge (`src/CircleBadge.js`) @emplums #195 
- [x] CircleOcticon (`src/CircleOcticon.js`) @emplums - No changes necessary
- [x] CounterLabel (`src/CounterLabel.js`) @emplums #196
- [x] Details (`src/Details.js`) @shawnbot #194
- [x] DonutChart (`src/DonutChart.js`) @shawnbot #183
- [x] DonutSlice (`src/DonutSlice.js`) @shawnbot #183
- [x] Dropdown (`src/Dropdown.js`) @shawnbot #192
- [x] Flash (`src/Flash.js`) @shawnbot 
- [x] FlexContainer (`src/FlexContainer.js`) @shawnbot
- [x] FlexItem (`src/FlexItem.js`) @shawnbot
- [x] Label (`src/Label.js`) @shawnbot 
- [x] Heading (`src/Heading.js`) @shawnbot 
- [x] Link (`src/Link.js`) @jonrohan https://github.com/primer/primer-react/pull/169
- [x] MergeStatus (`src/MergeStatus.js`) @jonrohan https://github.com/primer/primer-react/pull/171
- [x] OcticonButton (`src/OcticonButton.js`) @jonrohan https://github.com/primer/primer-react/pull/172
- [x] StateLabel (`src/StateLabel.js`) @jonrohan https://github.com/primer/primer-react/pull/173
- [x] Text (`src/Text.js`) @shawnbot 
- [x] TextInput (`src/TextInput.js`) @jonrohan https://github.com/primer/primer-react/pull/174
- [x] Tooltip (`src/Tooltip.js`) @jonrohan https://github.com/primer/primer-react/pull/176
- [x] UnderlineNav (`src/UnderlineNav.js`) @jonrohan https://github.com/primer/primer-react/pull/177
- [x] UnderlineNavLink (`src/UnderlineNavLink.js`) @jonrohan https://github.com/primer/primer-react/pull/179

### Docs / Examples
- [x] Replace all instances of color names without a step (`red`) with "stepped" equivalents (`red.5`) in all three color props: `bg`, `color`, and `borderColor` (see #185 for info). @emplums
- [x] Replace all instances of `tag="foo"` with `is="foo"` @emplums

### Etc.
- [x] `src/props.js` needs to be reorganized, and many of the helper functions from this can go. Once we're finished with the component migration, we can use eslint to figure out which functions aren't used anymore. @shawnbot #203
- [x] `src/theme.js` may need some love to match up with [all of the styled-system functions](https://jxnblk.com/styled-system/table) @shawnbot
