### ISSUE TITLE
[Batch] Improve slots implementation in PRC to enable React SSR compatibility & performance gain

### ISSUE THREAD

**Issue by siddharthkp** [primer/react#1690]
## Background

The current slot implementation isn't compatible with server-side rendering (SSR). It only renders the freeform main slot on the server and then adds other slots after mounting on the client (with useEffect) which is not a problem in client-only components like Overlay but can be a bad loading experience for other components with layout shift.

The tradeoffs considered at the time of building this component are mentioned in this comment: https://github.com/github/primer/issues/1224#issuecomment-1222450075

## Task 

Update the slots implementation to render consistently across the server and client. This will introduce a limitation that a slot needs to be a direct child of the slot container, deep nesting is not allowed. 

### Components to migrate

- [x] PageLayout: https://github.com/primer/react/pull/3036
- [x] TreeView: https://github.com/primer/react/pull/3097
- [x] CheckboxGroup: https://github.com/primer/react/pull/3146
- [x] RadioGroup: https://github.com/primer/react/pull/3146
- [x] FormControl https://github.com/primer/react/pull/3149
- [x] ActionList https://github.com/primer/react/pull/3173
- [x] NavList https://github.com/primer/react/pull/3173
- [x] MarkdownEditor (draft) https://github.com/primer/react/pull/3174 https://github.com/github/primer/issues/2090

### Related work

- [x] https://github.com/github/primer/issues/1936

### Clean up
- [x] Remove legacy slots implementation https://github.com/primer/react/pull/3205

**Comment by siddharthkp** [comment]
Another use case for this - https://github.com/orgs/github/issues/issues (behind feature flag)

https://user-images.githubusercontent.com/1863771/180964965-df092a4e-06c3-47bd-abf7-58fe41f6adac.mp4

As a stop gap, we moved the contents of leading visual inside text

**Comment by siddharthkp** [comment]
Another example where this falls short: https://github.com/github/primer/issues/1224

**Comment by lesliecdubs** [comment]
Hey @siddharthkp, would it be helpful to keep this one open for reference or should we go ahead and close? I have a draft in the Primer Roadmap backlog to revisit slots so it's definitely still on the radar. https://github.com/orgs/github/projects/2759/views/32?filterQuery=-no%3Afocus-area+-status%3A%22Inbox+%F0%9F%93%A5%22+-label%3Ainitiative+slots

**Comment by siddharthkp** [comment]
@lesliecdubs Late reply, but I think we should keep this open :)

Leaving here for future reference, we have a draft of the implementation in this closed PR: https://github.com/primer/react/pull/2525

**Comment by lesliecdubs** [comment]
👋🏻 @colebemis starting this week, could you please add a [`/status` update on this batch each week](https://github.com/github/design-infrastructure/blob/main/how-we-work/planning-and-tracking-work/updates.md#weekly-status-updates-required) (link for GitHub staff only) assuming this is still something you have in progress?

**Comment by colebemis** [comment]
### Trending


🟢 on track


### Target date


2023-04-21


### This Week


Migrated `CheckboxGroup`, `RadioGroup`, and `FormControl` to use the SSR-compatible slots implementation:
- [x] CheckboxGroup: https://github.com/primer/react/pull/3146
- [x] RadioGroup: https://github.com/primer/react/pull/3146
- [x] FormControl https://github.com/primer/react/pull/3149


### Next Week


- [ ] ActionList
- [ ] MarkdownEditor

**Comment by colebemis** [comment]
### Trending


🟢 on track


### Target date


2023-04-21


### This Week


Migrated `ActionList`, `NavList`, and `MarkdownEditor` to use the SSR-compatible slots implementation:
- [x] ActionList https://github.com/primer/react/pull/3173
- [x] NavList https://github.com/primer/react/pull/3173
- [x] MarkdownEditor https://github.com/primer/react/pull/3174


### Next Week


- [ ] Remove legacy slots implementation code

**Comment by lesliecdubs** [comment]
Hooray! 🎉 Thank you for the quick work on this one @colebemis!

![Young man in a black t-shirt claps emphatically and mouths the word "YES" with an intense face](https://user-images.githubusercontent.com/3902488/234151250-4fbb4fff-47f4-4abf-803a-e0743397aaaf.gif)
