### ISSUE TITLE
[tracking] Test updates

### ISSUE THREAD

**Issue by shawnbot** [primer/react#219]
This is a tracking issue for updating our component tests, originally discussed in #165.

### TODO
- [ ] List out all of the suites and/or tests marked as pending with `xdescribe()` and `xit()`.
- [ ] Identify the things we actually need to test for each component.
- [ ] Update each test suite accordingly.

### Components
- [ ] Avatar
- [ ] BorderBox
- [ ] ~Box 
- [ ] BranchName
- [ ] Button 
- [ ] ButtonDanger 
- [ ] ButtonLink
- [ ] ButtonOutline  
- [ ] ButtonPrimary 
- [ ] Caret
- [ ] CaretBox 
- [ ] CircleBadge 
- [ ] CircleOcticon 
- [ ] CounterLabel 
- [ ] Details
- [ ] DonutChart 
- [ ] DonutSlice
- [ ] Dropdown @emplums
- [ ] Flash @emplums
- [ ] FlexContainer @emplums
- [ ] FlexItem @emplums
- [ ] Label @emplums
- [ ] Heading @emplums
- [ ] Link @emplums
- [ ] MergeStatus @emplums
- [ ] OcticonButton @emplums
- [ ] StateLabel @emplums
- [ ] Text  @emplums
- [ ] TextInput @emplums
- [ ] UnderlineNav @emplums
- [ ] UnderlineNavLink @emplums
