### ISSUE TITLE
Primer-react v1 beta - release tracking

### ISSUE THREAD

**Issue by broccolini** [primer/react#24]
# Tracking v0.0.1-beta

### Must
- [x] Remove remaining css-in-js components @emplums
- [x] Update package.json @emplums 
- [x] Buttons @emplums 
- [x] Flash component @broccolini
- [x] Counter component @emplums 
- [x] StateLabel component @shawnbot
- [x] Label component @jonrohan 
- [x] Text component (typography utilities) @shawnbot #37

### Should
- [x] Add tests @shawnbot #21
- [x] Box ("Block"?) component @shawnbot https://github.com/primer/primer-react/pull/32
- [x] Heading component (part of primer-typography) @shawnbot #37
- [x] Update utilities map to cover all Primer utilities

### Could
- [ ] Flex component
- [ ] Tooltip component
