### ISSUE TITLE
Release Tracking

### ISSUE THREAD

**Issue by joshblack** [primer/react#3275]
| Last week | Value |
| :-------- | :---- |
| Issue     | N/A      |
| Conductor | @broccolinisoup |

## Timeline

* Monday
  * Identified breakage downstream with ActionList
* Tuesday
  * Fix breakage of ActionList in `main`
  * https://github.com/primer/react/pull/3267
  * https://github.com/primer/react/pull/3269
* Wednesday
  * Identified performance regression with respect to bundle size
  * https://github.com/primer/react/pull/3271
* Thursday
  * Unable to verify release in downstream dependencies
* Friday

## Checklist

* [x] Integration checks have passed downstream
* [ ] Stable release available on npm
* [ ] Downstream repos have been updated to latest

## Notes

* Integration PR is available here: https://gh.io/AAkp8pf
* Unable to verify release

**Comment by broccolinisoup** [comment]
Just adding a comment here as we don't have this week's release tracking issue yet. @colebemis just fyi primer nightly is currently down 😞 it has been failing since last week I guess. I'll debug it this week and see what is going on 👀
